# [global]
# address = "1.2.3.4"

[development]
address = "localhost"
port = 8000
workers= 2 # max(number_of_cpus, 2)
log = "normal"
template_dir = "dev_templates/"

[staging]
address = "0.0.0.0"
port = 80
workers = 2 # max(number_of_cpus, 2)
log = "normal"

[production]
address = "murmuring-atoll-34131.herokuapp.com"
port = 8000
workers = 2 # max(number_of_cpus, 2)
log = "critical"
template_dir = "prod_templates/"
